# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='updated_on',
        ),
    ]
